name: e_commerce
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1
  dots_indicator: ^4.0.1
  icons_plus: ^5.0.0
  lottie: ^3.3.2
  supabase: ^2.10.0
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  equatable: ^2.0.7
  hive_flutter: ^1.1.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^2.0.1
  shared_preferences: ^2.2.2
  bloc: ^9.0.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/svgs/
    - assets/lottie/
